...
contract Crowdfunding is Pausable, Ownable {
    ...
    event Contribute(address contributor, uint amount);
    ...
    function contribute() public payable beforeDeadline whenNotPaused {
        ...
        emit Contribute(msg.sender, msg.value);
    }
}

